key_name: "{{ lookup('env','KEY') }}"
cert_name: ""

name: "{{ lookup('env','NAME') | default('k8s', true) }}"

network_name: "{{ lookup('env','NETWORK') | default(name, true) }}"
subnet_name: "{{ lookup('env','NETWORK') | default(name, true) }}"
subnet_cidr: "{{ lookup('env','SUBNET_CIDR') | default('10.8.10.0/24', true) }}"
pod_subnet_cidr: "{{ lookup('env','POD_SUBNET_CIDR') | default('10.96.0.0/16', true) }}"
cluster_dns_ip: "{{ lookup('env','CLUSTER_DNS_IP') | default('10.96.0.10', true) }}"
network_mtu: 9148
router_name: "{{ lookup('env','NAME') | default(name, true) }}"
floating_ip_pools: "{{ lookup('env', 'FLOATING_IP_POOL') | default(omit, true) }}"
external_network_name: "{{ lookup('env', 'EXTERNAL_NETWORK') | default('public', true) }}"
#use_octavia: "{{ lookup('env', 'USE_OCTAVIA') | default('False', true) | bool }}"
use_octavia: "{{ lookup('env', 'USE_OCTAVIA') | default('False', true) | bool }}"
use_loadbalancer: "{{ lookup('env', 'USE_LOADBALANCER') | default('False', true) | bool }}"
block_storage_version: "{{ lookup('env', 'BLOCK_STORAGE_VERSION') | default('v2', true) }}"
ignore_volume_az: "{{ lookup('env', 'IGNORE_VOLUME_AZ') | default('false', true) | bool }}"


helm_include: "{{ lookup('env', 'INCLUDE_HELM') | default(false) }}"
helm_repos: "{{ lookup('env', 'HELM_REPOS').split(';') | default([], true) }}"
helm_install: "{{ lookup('env', 'HELM_INSTALL').split(';') | default([], true) }}"

#Change at your own risk
kubernetes_version: v1.17.0
kubernetes_ubuntu_version: 1.17.0-00
kubernetes_cni_ubuntu_version: 0.7.5-00
docker_version: 18.09.7-0ubuntu1~16.04.5

k8s_etcd_external_ip: "{% for item in groups ['k8s_master'] | map ('extract',hostvars,['ansible_default_ipv4','address']) | join(',') %}{{ item }}{% endfor %}"

# OpenStack env
openstack_k8s_password: "{{ lookup('env','OS_PASSWORD') }}"
openstack_k8s_username: "{{ lookup('env','OS_USERNAME') }}"
openstack_tenant_id: "{{ os_project_id }}"
openstack_domain_id: "{{ lookup('env','OS_PROJECT_DOMAIN_ID') }}"
openstack_domain_name: "{{ lookup('env', 'OS_USER_DOMAIN_NAME') }}"
openstack_region_name: "{{ lookup('env', 'OS_REGION_NAME') }}"

docker_registry: ""
docker_username: ""
docker_password: ""
graylog_host: ""
