---

- name: copy manifests
  copy:
    src: "{{ role_path }}/files/"
    dest: "/home/ubuntu/manifests/"

- name: Wait for API server to be up
  shell: "/usr/bin/kubectl get nodes"
  register: api_server_up
  retries: 30
  delay: 10
  until: api_server_up | success
  tags:
    - skip_ansible_lint

- name: kubectl apply RBAC roles
  command: kubectl apply -f /home/ubuntu/manifests/cloud-controller-manager-roles.yaml

- name: kubectl apply RBAC role bindings
  command: kubectl apply -f /home/ubuntu/manifests/cloud-controller-manager-role-bindings.yaml

- name: apply k8s-auth-policy.yaml
  command: kubectl apply -f /home/ubuntu/manifests/k8s-auth-policy.yaml

- name: copy syncconfig.yaml
  become: true
  copy:
   src: "{{ role_path }}/files/syncconfig.yaml"
   dest: "/etc/kubernetes/syncconfig.yaml"

- name: Retrieve kubectl configuration
  become: yes
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: admin.conf
    flat: yes
    fail_on_missing: yes
