- block:

  - name: Create daemonset to tune sysctls
    k8s:
      definition:
        apiVersion: apps/v1
        kind: DaemonSet
        metadata:
          name: tune-sysctls
          namespace: kube-system
          labels:
            app: tune-sysctls
        spec:
          selector:
            matchLabels:
              name: tune-sysctls
          template:
            metadata:
              labels:
                name: tune-sysctls
            spec:
              hostNetwork: true
              hostPID: true
              hostIPC: true
              tolerations:
              - operator: Exists
                effect: NoSchedule
              containers:
              - name: setsysctls 
                command:
                - sh
                - -c
                - |
                  while true; do
                    sysctl -w fs.inotify.max_user_watches=524288
                    sysctl -w net.core.somaxconn=10000
                    sysctl -w net.ipv4.ip_local_port_range='1024 65535'
                    sysctl -w net.netfilter.nf_conntrack_max=131072
                    echo never > /sys/kernel/mm/transparent_hugepage/enabled
                    echo never > /sys/kernel/mm/transparent_hugepage/defrag
                    sleep 10
                  done
                image: alpine:3.6
                imagePullPolicy: IfNotPresent
                resources: {}
                securityContext:
                  privileged: true
                volumeMounts:
                - name: sys
                  mountPath: /sys
              volumes:
              - name: sys
                hostPath:
                  path: /sys
