---

- import_tasks: asserts.yml

- name: remove tmp
  local_action: file path=/tmp/pki state=absent

- include_tasks: k8s_local.yml
  environment:
    OS_USERNAME: '{{ os_username }}'
    OS_PASSWORD: '{{ os_password }}'
    OS_PROJECT_NAME: '{{ os_project_name }}'
    OS_PROJECT_ID: '{{ os_project_id }}'
    OS_USER_DOMAIN_NAME: '{{ os_user_domain_name }}'
    OS_AUTH_URL: '{{ os_auth_url }}'
    OS_IDENTITY_API_VERSION: '{{ os_identity_api_version }}'
    OS_PROJECT_DOMAIN_ID: '{{ os_project_domain_id }}'
    OS_REGION_NAME: '{{ os_region_name }}'
    OS_INTERFACE: '{{ os_interface }}'
    validate_certs: '{{ os_validate_certs }}'
    name: '{{ os_project_name }}-subnet-1'
  tags: openstack

- include_tasks: k8s_base_tasks.yml

- include_tasks: k8s_etcd_tasks.yml
  when: inventory_hostname in groups ['k8s_master'] and staging is not defined

- include_tasks: k8s_init_tasks.yml
  when: inventory_hostname == 'k8s-master-1'

- include_tasks: k8s_join_tasks.yml
  when: inventory_hostname != 'k8s-master-1'

- include_tasks: k8s_tune_tasks.yml
  when: inventory_hostname == 'k8s-master-1'

- name: remove tmp
  local_action: file path=/tmp/pki state=absent

- block:
  - block:
    
    - import_tasks: k8s_metrics_tasks.yml
      tags: metrics
  
    - import_tasks: k8s_fluent-bit_tasks.yml  
      tags: flunt-bit
  
    - block:
  
      - include_tasks: k8s_istio_tasks.yml
  
      - include_tasks: k8s_istio_virtual_tasks.yml
    
      when: istio is defined

  when: inventory_hostname == 'k8s-master-1'

- include_tasks: k8s_lb_master.yml
  when: staging is not defined
